import Head from "next/head";
import Navbar from "@/components/navbar";

export default function Home() {
    return (
        <>
            <Head>
                <title>Stock.PI | Data Driven Stock Analysis</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/icon-favicon/android-chrome-192x192.png"
                />
            </Head>
            <main>
                <Navbar />
            </main>
        </>
    );
}
