import LandingStock from "@/components/LandingStocks";
import About from "@/components/about";
import Footer from "@/components/footer";
import Hero from "@/components/hero";
import Navbar from "@/components/navbar";
import Head from "next/head";

export default function Index() {
    return (
        <>
            <Head>
                <title>Stock.PI | Data Driven Stock Analysis</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" />
            </Head>
            <main>
                <Navbar />
                <Hero />
                <About />
                <LandingStock />
                <Footer />
            </main>
        </>
    );
}
